version: "3.9"
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./ms-api/db:/opt/db
  ms-api:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    entrypoint: /myapp/docker-entrypoint.sh
    volumes:
      - ./ms-api:/opt/app
      - .:/myapp
    ports:
      - '3000:3000'
      - '1234:1234'
    env_file:
      - .env
